name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at 00:00
env:
    NETLIFY_WEBHOOK_URL: ${{ secrets.NETLIFY_WEBHOOK_URL }}
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: POST to Build Hook
        run: curl -X POST -d {} $NETLIFY_WEBHOOK_URL
