name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 0 * * 0' # Once a day
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: POST to Build Hook
        run: curl -X POST -d {} $NETLIFY_WEBHOOK_URL
